### ISSUE TITLE
Serve index.html

### ISSUE THREAD

**Issue by robdodson** [PolymerLabs/polyserve#10]
Is it possible for polyserve to serve `index.html` so I don't need to type it out every time?

**Comment by mikaelharsjo** [comment]
+1

**Comment by rvinay88** [comment]
+1

**Comment by justinfagnani** [comment]
It does already? The default behavior of `send()` is to support `index.html` files.

**Comment by justinfagnani** [comment]
Oh, unless you mean something like #11

**Comment by robdodson** [comment]
yeah the output tells you to open `localhost:8080/components/gravatar-img/` but if you literally copy and paste that into the browser you get nothing, you have to add `index.html` to the end. Basically exactly what #11 is talking about

**Comment by klebba** [comment]
Additionally; if the URL were printed in the console like: `http://localhost:8080/components/my-component/` then I could Command + Double Click the link and Terminal (OSX) would launch it for me. Because the format is currently `localhost:8080/components/my-component/...` Terminal does not infer that its a URL. Boo.

**Comment by yufengg** [comment]
+1.
Even if it doesn't recognize it as a url, right now copying usually leads to manually deleting the "..." from the URL before hitting enter since it will most likely pick it up in the copy+paste.

**Comment by soma-cepel** [comment]
:+1:

**Comment by justinfagnani** [comment]
Fixed. From the command line, `/` redirects to `/components/{package_name}/` and from the polyserve express app `/` redirects to `./{package_name}/. The URL sent to the console is valid and in OS X works with ctrl-click->Open URL.
