### ISSUE TITLE
PR #117 broke polyserve on the CLI

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/polyserve#125]
Running `polyserve` with the CLI is broken since #117 has been merged.
I have bisected from the previous release to master and the merge commit of #117 has caused that running `./bin/polyserve` directly terminates after logging `no bower.json detected, using name "serve"` to the console. Polyserve is not running and can not process any requests.

**Comment by justinfagnani** [comment]
I have a fix for this. I'll send it out in a bit.

**Comment by TimvdLippe** [comment]
Another issue I found that if no `root` is specified, `send()` resolves files incorrectly. The fix is changing https://github.com/PolymerLabs/polyserve/blob/master/src/start_server.ts#L284 to

    const root = options.root || '.';

**Comment by justinfagnani** [comment]
@TimvdLippe I didn't see this behavior, but maybe I missed it. Can you describe a reproduction?

**Comment by TimvdLippe** [comment]
```shell
mkdir polyserve-bug
cd polyserve-bug/
echo "Success" > index.html
npm install polymerlabs/polyserve#startServers-fix
cd node_modules/polyserve
npm install
npm run build
cd ..
cd ..
./node_modules/polyserve/bin/polyserve
```
Open localhost:8080 in your browser

### Expected behavior

`Success` on your screen

### Actual behavior

`Not found` on screen


Note that opening `localhost:8080/home/tim/Projects/polyserve-bug` (e.g. the literal folder location of the project) does show `Success` on screen.

**Comment by TimvdLippe** [comment]
@justinfagnani I suppose you were not able to reproduce the issue above?

**Comment by justinfagnani** [comment]
I just pushed a fix

**Comment by TimvdLippe** [comment]
Oh oops I missed that one. Sorry!
