### ISSUE TITLE
Recursive redirect

### ISSUE THREAD

**Issue by DamandeepS** [PolymerLabs/polyserve#16]
It looks like I'm hitting some infinite recursion when using polyserve...
I cloned polycast repository and did this..

>polycasts/ep14-reusable-elements$>  polyserve
>Starting Polyserve on port 8080
>Serving components from bower_components
>File in this directory are available at localhost:8080/components/tiny-badge/...

When I direct the browser to ```http://localhost:8080/components/tiny-badge/demo.html```, The url redirects to
```http://localhost:8080/components/tiny-badge/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/. ```

An error message is displayed in chrome "ERR_TOO_MANY_REDIRECTS"

**Comment by VandeurenGlenn** [comment]
Are you also using windows ?

**Comment by DamandeepS** [comment]
yes, windows 7
node v0.12.0
npm v2.5.1

**Comment by robrez** [comment]
windows 7 here, too.
node: 0.10.34
npm:  1.4.28

**Comment by justinfagnani** [comment]
I think this was fixed a while ago. If it's still an issue, please re-open.
