### ISSUE TITLE
Why not "bowerserve"?

### ISSUE THREAD

**Issue by zenorocha** [PolymerLabs/polyserve#20]
> I just went through all `hello-world-*` and `*-boilerplate` repos from [webcomponents](https://github.com/webcomponents) removing Grunt build steps in favor of polyserve. Looks so much better, thanks for putting this together @justinfagnani.

Now we're using it in repos that doesn't even use Polymer so I was wondering why not renaming this project to `bowerserve`? Unless I'm missing something this seems like it can be used by any project registered on Bower.

What do you guys think?

**Comment by justinfagnani** [comment]
I don't really care that much, I just needed a name at the time.

I have wondered if there are Polymer-specific features that would be useful, but I don't have anything at the moment.

**Comment by zenorocha** [comment]
I see... from an open source perspective it might be good to have a broader name because you can attract a larger number of potencial contributors. And if it really solves a problem beyond Polymer-specific projects, why not?

**Comment by justinfagnani** [comment]
We're going to be adding a lot more Polymer specific things soon, so closing this now.

**Comment by zenorocha** [comment]
:+1: +1
