### ISSUE TITLE
gulp-polyserve

### ISSUE THREAD

**Issue by gertcuykens** [PolymerLabs/polyserve#33]
Can a PolymerLabs/gulp-polyserve be made so we can make build systems our self?

```
var gulp = require('gulp');
var watch = require('gulp-watch');
var browserSync = require('browser-sync').create();

gulp.task('polyserve', function(){
    ...
});

gulp.task('default', ['polyserve'], function() {
    browserSync.init({
        proxy: "localhost:8080"
    });
    gulp.watch(...);
});
```

https://github.com/PolymerLabs/polyserve/issues/26

https://github.com/PolymerElements/seed-element/issues/53

**Comment by LM450N** [comment]
For me PolyServe was created to solve path troubles during the standalone components development. I would like to keep my elements as clean as possible (without adding a _gulpfile_). I would prefer keep PolyServe separated and maybe improve this one by adding a _livereload_ option.

_Please don't hit me!_ :fearful:

**Comment by gertcuykens** [comment]
I agree that's why I did ask for a separate PolymerLabs/gulp-polyserve :)

**Comment by gertcuykens** [comment]
never mind i could configure browser_sync enough so i don't need polyserve anymore

**Comment by drwaky** [comment]
Hey @gertcuykens How do you configure your browser_sync to have the same behavior? Thanks! :)

**Comment by gertcuykens** [comment]
Don't remember the details of this old issue, this is what I am currently using, PS also take a look at https://github.com/PolymerElements/polymer-starter-kit

```
gulp.task('browser', function() {
  browserSync({
    port: 5000,
    notify: false,
    reloadOnRestart: true,
    logPrefix: 'BS',
    snippetOptions: {
      rule: {
        match: '<span id="browser-sync-binding"></span>',
        fn: function(snippet) { return snippet; }
      }
    },
    https: false,
    files: [".tmp/**/*.*", "app/**/*.*"],
    proxy: 'http://localhost:8080',
    serveStatic: ['.tmp', 'app']
  });
});
```
