### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/polyserve#35]
@justinfagnani can you do a release of polyserve? It's been 6 mo and there's a bunch of new stuff the npm release doesn't contain. 

Happy to help take ownership of this tool if you want to add me to publish:

    npm owner add ebidel

**Comment by justinfagnani** [comment]
I'll get one out today

**Comment by justinfagnani** [comment]
Just pushed 0.5.0 to npm

**Comment by ebidel** [comment]
Thanks!
