### ISSUE TITLE
dependency missing from npm module

### ISSUE THREAD

**Issue by danners** [PolymerLabs/polyserve#65]
Hi,
i run an automated build process that installs polyserve from npm.
Since the latest package update, the process was broken because polyserve wouldn't start anymore because of a missing npm "command-line-args". Can you please add it to the dependencies?

Thanks,
Simon

**Comment by justinfagnani** [comment]
Looking into this now. You're totally correct that the dependency is missing, but I haven't figured out yet why it's working on a clean clone on my machine. I'd like to understand how it's finding command-line-args and prevent this from happening again...

**Comment by justinfagnani** [comment]
Wow, I figured it out. A few days ago I accidentally ran an `npm i` in the wrong directory, a few levels up from all of my project folders. This caused a bunch of modules to resolve that shouldn't have, in every project of my machine, including in my "fresh install" folder.

Sorry about that, I'll have the fix published soon!
