### ISSUE TITLE
-o option stopped working

### ISSUE THREAD

**Issue by mvolkmann** [PolymerLabs/polyserve#85]
In the latest version of polyserve it seems that the -o option no longer works. I tested this on a PC and a Mac.

**Comment by FredKSchott** [comment]
Did you download polyserve from npm or github? This was just fixed in `master` but a new version hasn't been cut yet. 

@justinfagnani can you give my npm perms to publish a new build?

**Comment by mvolkmann** [comment]
I got the 0.10.0 version from npm.

**Comment by FredKSchott** [comment]
This has been fixed and pushed to npm
